### ISSUE TITLE
is this used in production ?

### ISSUE THREAD

**Issue by notedit** [ernado/stun#23]
i am happy to do some test

**Comment by ernado** [comment]
Hi! Currently this package is used only for research.
Basic stun server implementation (that will answer for binding requests) will be released shortly.

**Comment by notedit** [comment]
any play for turn server?

**Comment by ernado** [comment]
@notedit https://github.com/cydev/tech-status
Turn server implementation is planned too and will start after basic stun tooling (server, client and benchmark) are released. 
I think it will be stable in 2017Q1.

Until that my advice is to use [coturn](https://github.com/coturn/coturn) for TURN and STUN, seems mature and feature-rich.

**Comment by notedit** [comment]
i am using  coturn for now,  i want to do more hack,  c  is more troublesome than go.

hope see your turn server. 👍

**Comment by notedit** [comment]
there is another repo.   https://github.com/pixelbender/go-stun

**Comment by ernado** [comment]
@notedit It seems to lack what it declares (there are no turn, nor ice implementation) and state of repo is unclear for me.

**Comment by notedit** [comment]
yes  that repo is wip.    i  can give you some test feedback  when you almost done.

**Comment by ernado** [comment]
You can use the https://github.com/gortc/gortcd now as TURN server.
