### ISSUE TITLE
long-term credential ?

### ISSUE THREAD

**Issue by notedit** [ernado/stun#29]
any long-term credential mechanism like coturn?

**Comment by ernado** [comment]
Hi! I think user handling is out of scope of stun implementation.
This package implements only RFC, not the applications (but I think I will add simple stun server and some utilities as subpackages).
Also there is [NewLongTermIntegrity](https://godoc.org/github.com/ernado/stun#NewLongTermIntegrity) function, so it is already available to check credentials for particular stun message.
```go
m := new(stun.Message)
m.ReadFrom(conn) // conn is io.Reader
i := stun.NewLongTermIntegrity("username", "realm", "password")
if err := i.Check(m); err != nil {
    fmt.Println("check failed:", err)
}
```

It definitely will be in **turn server**, tho.

**Comment by notedit** [comment]
ye   it better be in a  server module
